apiVersion : apps/v1
kind: Deployment
metadata:
  name: vamsipensionmicroservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vamsipensionmicroservice
  template:
    metadata:
      labels:
        app: vamsipensionmicroservice 
    spec:
      containers:
        - name: vamsipensionmicroservice 
          image: pmsregistery.azurecr.io/vamsipensionmicroservice
          ports:
          - containerPort: 80